void open_session(void *p = 0);

void theta() {
//=========Macro generated by ROOT version6.19/02
//=========for tree "events" (Mon May 10 19:19:50 2021)
//===This macro can be opened from a TreeViewer session after loading
//===the corresponding tree, or by running root with the macro name argument

   open_session();
}

void open_session(void *p = 0) {
   gSystem->Load("libTreeViewer");
   TTreeViewer *treeview = (TTreeViewer *) p;
   if (!treeview) treeview = new TTreeViewer();
   TTree *tv_tree = (TTree*)gROOT->FindObject("events");
   TFile *tv_file = (TFile*)gROOT->GetListOfFiles()->FindObject("output_ISRoff_alphaS13.root");
   if (!tv_tree) {
      if (!tv_file) tv_file = new TFile("output_ISRoff_alphaS13.root");
      if (tv_file)  tv_tree = (TTree*)tv_file->Get("events");
      if(!tv_tree) {
         printf("Tree %s not found", "events");
         return;
      }
   }

   treeview->SetTreeName("events");
   treeview->SetNexpressions(10);
//         Set expressions on axis and cut
   TTVLVEntry *item;
//   X expression
   item = treeview->ExpressionItem(0);
   item->SetExpression("acos(Particle.momentum.z/sqrt(Particle.momentum.x**2+Particle.momentum.y**2+Particle.momentum.z**2))", "~theta");
//   Y expression
   item = treeview->ExpressionItem(1);
   item->SetExpression("", "-empty-");
//   Z expression
   item = treeview->ExpressionItem(2);
   item->SetExpression("", "-empty-");
//   Cut expression
   item = treeview->ExpressionItem(3);
   item->SetExpression("acos(Particle.momentum.z/sart(Particle.momentum.x**2+Particle.momentum.y**2+Particle.momentum.z**2))", "~theta");
//         Scan list
   item = treeview->ExpressionItem(4);
   item->SetExpression("", "Scan box");
//         User defined expressions
   item = treeview->ExpressionItem(5);
   item->SetExpression("acos(Particle.momentum.z/sqrt(Particle.momentum.x**2+Particle.momentum.y**2+Particle.momentum.z**2))", "~theta", kFALSE);
   item = treeview->ExpressionItem(6);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(7);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(8);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(9);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(10);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(11);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(12);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(13);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(14);
   item->SetExpression("", "-empty-", kFALSE);
//--- session object
   TTVSession* tv_session = new TTVSession(treeview);
   treeview->SetSession(tv_session);
//--- Connect first record
   tv_session->First();
}
