void open_session(void *p = 0);

void cuts() {
//=========Macro generated by ROOT version6.19/02
//=========for tree "jetratio" (Mon Apr 26 19:42:12 2021)
//===This macro can be opened from a TreeViewer session after loading
//===the corresponding tree, or by running root with the macro name argument

   open_session();
}

void open_session(void *p = 0) {
   gSystem->Load("libTreeViewer");
   TTreeViewer *treeview = (TTreeViewer *) p;
   if (!treeview) treeview = new TTreeViewer();
   TTree *tv_tree = (TTree*)gROOT->FindObject("jetratio");
   TFile *tv_file = (TFile*)gROOT->GetListOfFiles()->FindObject("jetratio_all.root");
   if (!tv_tree) {
      if (!tv_file) tv_file = new TFile("jetratio_all.root");
      if (tv_file)  tv_tree = (TTree*)tv_file->Get("jetratio");
      if(!tv_tree) {
         printf("Tree %s not found", "jetratio");
         return;
      }
   }

   treeview->SetTreeName("jetratio");
   treeview->SetNexpressions(10);
//         Set expressions on axis and cut
   TTVLVEntry *item;
//   X expression
   item = treeview->ExpressionItem(0);
   item->SetExpression("Jet_algorithm", "~Jet_algorithm");
//   Y expression
   item = treeview->ExpressionItem(1);
   item->SetExpression("alpha_S", "~alpha_S");
//   Z expression
   item = treeview->ExpressionItem(2);
   item->SetExpression("Jet_ratio", "~Jet_ratio");
//   Cut expression
   item = treeview->ExpressionItem(3);
   item->SetExpression("(R==0.5)&&(Jet_algorithm==1)&&(E_cut==0)", "~R5,antikt");
//         Scan list
   item = treeview->ExpressionItem(4);
   item->SetExpression("", "Scan box");
//         User defined expressions
   item = treeview->ExpressionItem(5);
   item->SetExpression("(R==0.5)&&(Jet_algorithm==1)&&(E_cut==0)", "~R5,antikt", kTRUE);
   item = treeview->ExpressionItem(6);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(7);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(8);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(9);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(10);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(11);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(12);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(13);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(14);
   item->SetExpression("", "-empty-", kFALSE);
//--- session object
   TTVSession* tv_session = new TTVSession(treeview);
   treeview->SetSession(tv_session);
//--- Connect first record
   tv_session->First();
}
